## Introduction to Tensor Flow
A tensor is a generalization of vectors and matrices to potentially higher dimensions. TensorFlow represents tensor as n-dimensional arrays of base data types
Each tensor has a data type and a  shape

$\bf{Data}$ $\bf{Types}$ $\bf{Includes:}$
- float32
- int32
- string
- others

$\bf{Shape:}$ Represents the dimension of data

In [1]:
import tensorflow as tf
string = tf.Variable("String", tf.string)
number = tf.Variable(329, tf.int16)
floating = tf.Variable(3.567, tf.float64)
print(string,'\n', number, '\n',floating)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'String'> 
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=329> 
 <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.567>


### Rank/Degree of Tensors
Rank or degree means the number of dimensions involved in the tensor. What is created above for example is a tensor of zero dimension also called a scalar.

In [22]:
rank2Tensor = tf.Variable([['Test', 'OK'], ['Test', 'OK']], tf.string)
rank2_Tensor = tf.Variable([['Test', 'OK']], tf.string)
rank1_Tensor = tf.Variable(['Test', 'OK'], tf.string)

In [23]:
print(tf.rank(rank2Tensor), tf.rank(rank2_Tensor),  tf.rank(rank1_Tensor))


tf.Tensor(2, shape=(), dtype=int32) tf.Tensor(2, shape=(), dtype=int32) tf.Tensor(1, shape=(), dtype=int32)


The level of nesting of our data types is another way of looking at rank/degree

### Shapes of a Tensor
How many items we have in each dimension

In [26]:
rank2Tensor1 = tf.Variable([['Test', 'OK', 'Next'], ['Test', 'OK', 'Next']], tf.string)
print(rank2Tensor.shape, rank2_Tensor.shape,  rank1_Tensor.shape, rank2Tensor1.shape)


(2, 2) (1, 2) (2,) (2, 3)


### Changing Shape
Number of elements of a tensor is the product of the sizes of all its shapes. There can be many shapes with same number of elements

In [39]:
tensor1 = tf.ones([1, 2, 3])
print('Tensor1', tensor1)
tensor2 = tf.reshape(tensor1, [2, 3, 1]) #rehspae to shape (2, 3, 1)
tensor3= tf.reshape(tensor1, [3, -1]) # -1 is a way to automatically size the dimension to match number of elements
print('\nTensor2 : \n',tensor2, '\nTensor3 :\n ',tensor3)              # in this case that would mean shape of (3, 3) in order to preserve all 6 elements


Tensor1 tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)

Tensor2 : 
 tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32) 
Tensor3 :
  tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


### Types of Tensors
- Variable
- Constant
- Placeholder
- SparseTensor

Only Variables can be mutated(meaning changed during execution)

### Evaluating Tensors
Evaluating a tensor meaning get its value. Since tensors are partially complete computation, we will need to run something called a session to evaluate a tensor.



In [40]:
with tf.compat.v1.Session() as sess:  #  creates a session using the default graph
    tensor1.eval()           #  tensor will of courrse 


NotImplementedError: eval is not supported when eager execution is enabled, is .numpy() what you're looking for?

Hmmm...https://stackoverflow.com/questions/55142951/tensorflow-2-0-attributeerror-module-tensorflow-has-no-attribute-session

Stack overflow check for workaround

In [2]:
import tensorflow as tf
print(tf.__version__)

with tf.compat.v1.Session() as sess:
  constant = tf.constant([1, 2, 3])
  tft = constant*constant
  print(tft.eval())

2.11.0
[1 4 9]


### Sources

Most of the information is taken directly from the TensorFlow website which can be found below
https://www.tensorflow.org/guide/tensor